swiftlintのシリアスなメッセージを出ないようにする
Nyoho/HatebLine pull request #19
Opened 2017-08-11 08:27 UTC by eiel

```
$ cd HatebLine
$ swiftlint
```

した時に、0 seriousになるように修正をした。
```
Done linting! Found 57 violations, 0 serious in 20 files.
```

2017-08-11 08:31 UTC, eiel commented on HatebLine/AppDelegate.swift
> -        // The persistent store coordinator for the application. This implementation creates and returns a coordinator, having added the store for the application to it. (The directory for the store
長過ぎるっていわれたので、消してもよかったけど改行を入れてごまかした。

2017-08-11 08:31 UTC, eiel commented on HatebLine/AppDelegate.swift
> -        // Returns the managed object context for the application (which is already bound to the persistent store coordinator for the application.) This property is optional since there are legitimat
長過ぎるっていわれたので改行をいれてごまかした。

2017-08-11 08:31 UTC, eiel commented on HatebLine/CommentsViewController.swift
> +        static func decode(_ extractor: Extractor) throws -> Comment {
3文字以上にしろって言われたので変えた

2017-08-11 08:31 UTC, eiel commented on HatebLine/Helper.swift
> -                t.append(NSAttributedString(string: comma + space + "\(tag)", attributes: [NSForegroundColorAttributeName: NSColor.headerColor, NSFontAttributeName: NSFont.systemFont(ofSize: NSFont.s
長過ぎるって言われたので分割した。

2017-08-11 08:31 UTC, eiel commented on HatebLine/JKTableView.swift
> -            row = row + 1
+= でかけっていわれた

2017-08-11 08:31 UTC, eiel commented on HatebLine/MainWindowController.swift
> -            let webvc = segue.destinationController as! WebViewController
`as!`つかうなっていわれたので、 Optionに変換してそもそも期待した型じゃない場合は何かおかしいのでabortするようにした。

2017-08-11 08:31 UTC, eiel commented on HatebLine/TimelineViewController.swift
> -                guard let bookmarkUrl = item["bookmarkUrl"] as? String else { continue }
長過ぎるので
* newBoorkmark
  * createBookmark
  * updateBookmark
に分割した。

そもそもViewControllerにあるべき処理ではない気がするので、別のクラスにしたいがそれは別の機会に。

2017-08-11 15:20 UTC, Nyoho commented
```
Done linting! Found 3970 violations, 840 serious in 281 files.
```
うちでやるとこんなにいっぱい出た。

2017-08-11 15:24 UTC, Nyoho reviewed
こんなスコープが短いのでも3文字以上にするのかーストイックだなー

2017-08-11 15:24 UTC, Nyoho commented on HatebLine/CommentsViewController.swift
> +        static func decode(_ extractor: Extractor) throws -> Comment {
こんなスコープが短いのでも3文字以上にするのかーストイックだなー

2017-08-11 15:50 UTC, Nyoho commented on HatebLine/TimelineViewController.swift
> -                guard let bookmarkUrl = item["bookmarkUrl"] as? String else { continue }
ナイス〜! そこやらんといけんと思いながらなんもしてなかったー!

2017-08-29 02:05 UTC, eiel commented on HatebLine/CommentsViewController.swift
> +                ($0.comment ?? "").isEmpty || !($0.tags ?? []).isEmpty
短い変数使いたいならこうしろって感じがした。

2017-08-29 02:06 UTC, eiel commented on .swiftlint.yml
> +  Carthage
Carthageディレクトリ無視したら快適になりました。

2017-08-30 02:35 UTC, Nyoho requested changes
```
identifier_name:
  min_length: 1
```
これもお願いします。
その上で `extractor` を `e` に戻したりしてみるという具合で

2017-08-30 02:35 UTC, Nyoho commented on .swiftlint.yml
> +  Carthage
よーしこれつけてもらうかー

```yaml
identifier_name:
  min_length: 1
```

2017-08-30 04:24 UTC, eiel commented
@Nyoho 
> その上で extractor を e に戻したりしてみるという具合で

警告はだすってことでええんかのう

2017-09-07 15:28 UTC, Nyoho commented
@eiel 
警告は出ているけどエラーが消えるのでOKとしよう。

2017-09-08 02:02 UTC, eiel commented
じゃあ、次に進むかとおもったらマージされていなかった。

2017-09-08 02:51 UTC, Nyoho commented
我々人類は次のステージへ進まなければならない。スクワッシュアンドマージによる遂行を願うぞ。

2017-09-08 02:51 UTC, merged